### ISSUE TITLE
Feature Request: need support VS2017 & VS2019

### ISSUE THREAD

**Issue by vincedan** [SLaks/VSEmbed#7]
VSEmbed is a really amazing tool. MS has made changes in VS2017& VS2019 in setup & editor & Roslyn, could your skeleton supports them too？

**Comment by SLaks** [comment]
This is tricky; locating the editor DLLs with the new deployment model is much more complex.

**Comment by vincedan** [comment]
got your idea and thank you for sharing VSEmbed.  I am trying to find a way to make a tool which can run standalone and integrated in VS studio both. for same reason, I need embedding vs code editor.  It is hard to find good example on internet. but VSEmbed is a really amazing sample..
Thanks again. @SLaks.
